### ISSUE TITLE
the emoji didn't work....

### ISSUE THREAD

**Issue by WitnessDlx** [carpedm20/emoji#54] opened 2017-04-12 16:18 UTC
as you can see , i do it as example ,but didn't work
```python
 -*- coding: <encoding unicode > -*-

import emoji
print(emoji.emojize('Python is :thumbs_up_sign:'))`
```
the Result is:
```python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:38:22) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
Python is :thumbs_up_sign:
>>> 
```

**Comment by Maryom** [comment] 2017-04-15 18:00
I faced same issue but the below worked with me, Did you try it?

`print(emoji.emojize('Python is :thumbsup:', use_aliases=True))`

**Comment by WitnessDlx** [comment] 2017-04-16 06:12
yeah , I try .
```python
# -*- coding: <encoding unicode > -*-

import emoji
print(emoji.emojize('Python is :thumbsup:', use_aliases=True))

>>> ================================ RESTART ================================
>>> 
Traceback (most recent call last):
  File "C:\Users\Witness\Desktop\aa.py", line 4, in <module>
    print(emoji.emojize('Python is :thumbsup:', use_aliases=True))
  File "D:\python34\lib\idlelib\PyShell.py", line 1342, in write
    return self.shell.write(s, self.tags)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 10-10: Non-BMP character not supported in Tk
>>> 

```

can you solve this?

**Comment by Maryom** [comment] 2017-04-16 13:13
Sorry I don't know how to solve it.

**Comment by truthdoug** [comment] 2020-08-03 14:26
This is an issue in how Tk renders (or doesn't render) the unicode produced by this package. It cannot be fixed by this package. 

This issue can be closed.

**Closed** 2021-01-23 14:49 UTC

**Comment by rose-wasilewska** [comment] 2024-01-30 22:17
Okie, girls... It is probably to late but it might help someone else here :) (emoticons rule!)
Maybe the problem is that you copied the code from other websites.
Try to write with your own hands.
1. Write to the CLI: pip install emoji
2. Start writing code:
1 import emoji
2 print(emoji.emojize( "This is slightly smiling emoji :slightly_smiling_face: ")

I had the same problem. But after I wrote it myself without copying the 'print(...  , it worked!

**Comment by rose-wasilewska** [comment] 2024-01-30 22:20
oh the 🙂 is in the code slightly_smiling_face ofc. Github just trots out :D
